
#HotOrNot Config
[general]
	#This sets the maximum durability for the mitts.
	#Range: > 1
	mitts_durability = 12000
	#This sets an items on a cold fluid whitelist. It will have the cold fluid effect.
	cold_whitelisted_items = []
	#This sets an item on a fluid blacklist. It won't be affected.
	blacklisted_items = []
	#This sets the temperature when a hot fluid should start burning the player (in kelvin).
	#Range: > 1
	hot_temperature = 1300
	#This sets an item on a gaseous fluid whitelist. It will have the gaseous fluid effect.
	gaseous_whitelisted_items = []
	#This sets an item as a mitts item. It prevents all effects.
	mitts_items = []
	#This sets an item on a hot fluid whitelist. It will have the hot fluid effect.
	hot_whitelisted_items = []
	#This sets the temperature when a cold fluid should add effects to the player (in kelvin).
	#Range: > 1
	cold_temperature = 273
	#This sets whether gaseos effect for a fluid should be enabled.
	gaseous = false
	#This sets whether an item that contains a fluid will have a tooltip that they are gaseous, too hot or too cold.
	tooltips = true

